---
#- name: Check to see if rpcap in already installed 
#  action: shell /opt/extrahop/sbin/rpcapd -v  
#  register: rpcap_version
#- debug: msg="{{rpcap_version.stdout}}"
- name: load variables
  include_vars: "{{ vars_file }}"
- name: Grab rpcap from Extrahop
  get_url: 
    url: https://{{ extrahopIP }}/tools/rpcapd_4.1.24504_amd64.deb 
    dest: "/home/{{ ansible_env.SUDO_USER }}/rpcap.deb" 
    validate_certs: no
- name: Install .deb
  apt:
    deb: "/home/{{ ansible_env.SUDO_USER }}/rpcap.deb"
    dpkg_options: 'i'
    state: present
- name: Copy rpcapd.ini file
  copy:
    src: rpcapd.ini  
    dest: /opt/extrahop/etc/rpcapd.ini
    owner: "{{ ansible_env.SUDO_USER }}"
- name:  Restart Service
  action: command /etc/init.d/rpcapd restart
  register: result
- debug: var=result.stdout

  


   
